# Generated by Django 4.1.5 on 2023-03-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('solve a quiz', 'Can solve a quiz '), ('change profile', 'Can change his profile')]},
        ),
    ]
