# Generated by Django 4.1.5 on 2023-03-10 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'permissions': (('solve a quiz', 'Can solve a quiz '), ('change profile', 'Can change his profile'))},
        ),
    ]
