# Generated by Django 4.1.5 on 2023-03-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='user_score',
        ),
        migrations.AddField(
            model_name='userscore',
            name='user_score_easy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='user_score_hard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='user_score_medium',
            field=models.IntegerField(default=0),
        ),
    ]
