# Generated by Django 4.1.5 on 2023-04-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additionalStuff', '0002_alter_dictionary_topic_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
