# Generated by Django 4.1.5 on 2023-04-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additionalStuff', '0003_dictionary_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='description',
            field=models.TextField(default=' — '),
        ),
    ]
