# Generated by Django 4.1.5 on 2023-03-17 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScores',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_score_1', models.IntegerField()),
                ('user_score_2', models.IntegerField()),
                ('user_score_3', models.IntegerField()),
                ('user_score_4', models.IntegerField()),
                ('user_score_5', models.IntegerField()),
                ('user_score_6', models.IntegerField()),
                ('user_score_7', models.IntegerField()),
                ('user_score_8', models.IntegerField()),
                ('user_score_9', models.IntegerField()),
                ('user_score_10', models.IntegerField()),
                ('user_score_11', models.IntegerField()),
                ('user_score_12', models.IntegerField()),
            ],
        ),
    ]
