# Generated by Django 4.1.5 on 2023-03-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscores',
            name='user_score_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='user_score_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='user_score_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='user_score_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='user_score_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='user_score_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='user_score_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='user_score_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='user_score_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='user_score_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='user_score_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='user_score_9',
            field=models.IntegerField(default=0),
        ),
    ]
