# Generated by Django 4.1.5 on 2023-03-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_13',
            new_name='user_score_1',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_14',
            new_name='user_score_10',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_15',
            new_name='user_score_2',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_16',
            new_name='user_score_3',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_17',
            new_name='user_score_4',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_18',
            new_name='user_score_5',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_19',
            new_name='user_score_6',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_20',
            new_name='user_score_7',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_21',
            new_name='user_score_8',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_22',
            new_name='user_score_9',
        ),
    ]
