# Generated by Django 4.1.5 on 2023-03-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_rename_user_score_13_userscores_user_score_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_1',
            new_name='user_score_13',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_10',
            new_name='user_score_14',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_2',
            new_name='user_score_15',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_3',
            new_name='user_score_16',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_4',
            new_name='user_score_17',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_5',
            new_name='user_score_18',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_6',
            new_name='user_score_19',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_7',
            new_name='user_score_20',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_8',
            new_name='user_score_21',
        ),
        migrations.RenameField(
            model_name='userscores',
            old_name='user_score_9',
            new_name='user_score_22',
        ),
    ]
