# Generated by Django 4.1.5 on 2023-03-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_rename_user_score_1_userscores_user_score_13_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscores',
            name='user_score_23',
            field=models.IntegerField(default=0),
        ),
    ]
