# Generated by Django 4.1.5 on 2023-04-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0009_studentgroup_studentgroupuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='group',
            field=models.CharField(error_messages={'unique': 'Данное имя группы уже используется'}, max_length=255, unique=True),
        ),
    ]
