# Generated by Django 4.1.5 on 2023-04-08 10:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userProfile', '0010_alter_studentgroup_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentGroup',
            new_name='StudentsGroup',
        ),
    ]
