# Generated by Django 4.1.5 on 2023-03-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionOptions',
            new_name='QuestionOption',
        ),
    ]
