# Generated by Django 4.1.5 on 2023-03-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_topicmaterials_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmaterials',
            name='videos',
            field=models.URLField(default=''),
        ),
    ]
