# Generated by Django 4.1.5 on 2023-03-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_topicmaterials_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmaterials',
            name='id',
        ),
        migrations.AlterField(
            model_name='topicmaterials',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.topic'),
        ),
    ]
