# Generated by Django 4.1.5 on 2023-03-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_topicmaterials_id_alter_topicmaterials_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicmaterials',
            old_name='photos',
            new_name='mainPhoto',
        ),
        migrations.RenameField(
            model_name='topicmaterials',
            old_name='presentation',
            new_name='presentations',
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.IntegerField()),
                ('photo', models.URLField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.topic')),
            ],
        ),
    ]
