# Generated by Django 4.1.5 on 2023-03-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_photos_topicmaterials_mainphoto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicmaterials',
            old_name='presentations',
            new_name='presentation',
        ),
    ]
