# Generated by Django 4.1.7 on 2023-03-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_presentations_topicmaterials_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='microTopic',
            field=models.IntegerField(default=1),
        ),
    ]
