# Generated by Django 4.1.5 on 2023-03-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_photos_microtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmaterials',
            name='photos',
            field=models.URLField(default=''),
        ),
    ]
