# Generated by Django 4.1.5 on 2023-03-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_topicmaterials_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
