# Generated by Django 4.1.5 on 2023-04-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_delete_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmaterials',
            name='personInfo',
            field=models.TextField(default=''),
        ),
    ]
